import java.io.File;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
    		File file = new File("/Volumes/Seagate Backup Plus Drive");
    		if(file.exists()) {
    			System.out.println(file.getFreeSpace());
    		}
        return true;
    }
    
    public static void main(String[] args) {
    	File file = new File("/Volumes/Seagate Backup Plus Drive");
		if(file.exists()) {
			System.out.println(file.getFreeSpace());
		}
    }
}
